checks:
    php: true
filter: {  }
coding_style:
    php: {  }

filter:
    excluded_paths: [vendor/*, Tests/*, bin/*]

tools:
    external_code_coverage:
        timeout: 1800
        runs: 2
    php_sim: true
    php_mess_detector: true
    php_cs_fixer: true
    php_analyzer: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_cpd:
        enabled: true
        excluded_dirs:        [vendor, tests, bin]
    php_loc:
        enabled: true
        excluded_dirs:        [vendor]
    php_pdepend:
        enabled: true
        excluded_dirs:        [vendor, Tests, bin]
